###
GET https://api.iextrading.com/1.0/stock/market/batch?symbols=GOOG,TSLA,MSFT,FB,MDB,PFE,S&types=news,quote,chart&range=3m&last=10 HTTP/1.1
Content-Type: application/json


###
@contentType = application/json
@types= peers,news,quote,chart
@range= 3m
@last= 10
GET https://api.iextrading.com/1.0/stock/market/
batch?
symbols=msft,mdb,cag,pfe,ndaq
&types={{types}}
&range={{range}}
&last={{last}}
Content-Type: {{contentType}}
